# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kernel_error/Desktop/dev/umse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kernel_error/Desktop/dev/umse

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kernel_error/Desktop/dev/umse/CMakeFiles /home/kernel_error/Desktop/dev/umse/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kernel_error/Desktop/dev/umse/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named umse

# Build rule for target.
umse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umse
.PHONY : umse

# fast build rule for target.
umse/fast:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/build
.PHONY : umse/fast

src/browse.o: src/browse.c.o
.PHONY : src/browse.o

# target to build an object file
src/browse.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/browse.c.o
.PHONY : src/browse.c.o

src/browse.i: src/browse.c.i
.PHONY : src/browse.i

# target to preprocess a source file
src/browse.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/browse.c.i
.PHONY : src/browse.c.i

src/browse.s: src/browse.c.s
.PHONY : src/browse.s

# target to generate assembly for a file
src/browse.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/browse.c.s
.PHONY : src/browse.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/config.c.s
.PHONY : src/config.c.s

src/file.o: src/file.c.o
.PHONY : src/file.o

# target to build an object file
src/file.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/file.c.o
.PHONY : src/file.c.o

src/file.i: src/file.c.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/file.c.i
.PHONY : src/file.c.i

src/file.s: src/file.c.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/file.c.s
.PHONY : src/file.c.s

src/input.o: src/input.c.o
.PHONY : src/input.o

# target to build an object file
src/input.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/input.c.o
.PHONY : src/input.c.o

src/input.i: src/input.c.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/input.c.i
.PHONY : src/input.c.i

src/input.s: src/input.c.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/input.c.s
.PHONY : src/input.c.s

src/listview.o: src/listview.c.o
.PHONY : src/listview.o

# target to build an object file
src/listview.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/listview.c.o
.PHONY : src/listview.c.o

src/listview.i: src/listview.c.i
.PHONY : src/listview.i

# target to preprocess a source file
src/listview.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/listview.c.i
.PHONY : src/listview.c.i

src/listview.s: src/listview.c.s
.PHONY : src/listview.s

# target to generate assembly for a file
src/listview.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/listview.c.s
.PHONY : src/listview.c.s

src/output.o: src/output.c.o
.PHONY : src/output.o

# target to build an object file
src/output.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/output.c.o
.PHONY : src/output.c.o

src/output.i: src/output.c.i
.PHONY : src/output.i

# target to preprocess a source file
src/output.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/output.c.i
.PHONY : src/output.c.i

src/output.s: src/output.c.s
.PHONY : src/output.s

# target to generate assembly for a file
src/output.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/output.c.s
.PHONY : src/output.c.s

src/screen.o: src/screen.c.o
.PHONY : src/screen.o

# target to build an object file
src/screen.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/screen.c.o
.PHONY : src/screen.c.o

src/screen.i: src/screen.c.i
.PHONY : src/screen.i

# target to preprocess a source file
src/screen.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/screen.c.i
.PHONY : src/screen.c.i

src/screen.s: src/screen.c.s
.PHONY : src/screen.s

# target to generate assembly for a file
src/screen.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/screen.c.s
.PHONY : src/screen.c.s

src/static.o: src/static.c.o
.PHONY : src/static.o

# target to build an object file
src/static.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/static.c.o
.PHONY : src/static.c.o

src/static.i: src/static.c.i
.PHONY : src/static.i

# target to preprocess a source file
src/static.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/static.c.i
.PHONY : src/static.c.i

src/static.s: src/static.c.s
.PHONY : src/static.s

# target to generate assembly for a file
src/static.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/static.c.s
.PHONY : src/static.c.s

src/str.o: src/str.c.o
.PHONY : src/str.o

# target to build an object file
src/str.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/str.c.o
.PHONY : src/str.c.o

src/str.i: src/str.c.i
.PHONY : src/str.i

# target to preprocess a source file
src/str.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/str.c.i
.PHONY : src/str.c.i

src/str.s: src/str.c.s
.PHONY : src/str.s

# target to generate assembly for a file
src/str.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/str.c.s
.PHONY : src/str.c.s

src/sys.o: src/sys.c.o
.PHONY : src/sys.o

# target to build an object file
src/sys.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/sys.c.o
.PHONY : src/sys.c.o

src/sys.i: src/sys.c.i
.PHONY : src/sys.i

# target to preprocess a source file
src/sys.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/sys.c.i
.PHONY : src/sys.c.i

src/sys.s: src/sys.c.s
.PHONY : src/sys.s

# target to generate assembly for a file
src/sys.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/sys.c.s
.PHONY : src/sys.c.s

src/umse.o: src/umse.c.o
.PHONY : src/umse.o

# target to build an object file
src/umse.c.o:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/umse.c.o
.PHONY : src/umse.c.o

src/umse.i: src/umse.c.i
.PHONY : src/umse.i

# target to preprocess a source file
src/umse.c.i:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/umse.c.i
.PHONY : src/umse.c.i

src/umse.s: src/umse.c.s
.PHONY : src/umse.s

# target to generate assembly for a file
src/umse.c.s:
	$(MAKE) -f CMakeFiles/umse.dir/build.make CMakeFiles/umse.dir/src/umse.c.s
.PHONY : src/umse.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... umse"
	@echo "... src/browse.o"
	@echo "... src/browse.i"
	@echo "... src/browse.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/listview.o"
	@echo "... src/listview.i"
	@echo "... src/listview.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/screen.o"
	@echo "... src/screen.i"
	@echo "... src/screen.s"
	@echo "... src/static.o"
	@echo "... src/static.i"
	@echo "... src/static.s"
	@echo "... src/str.o"
	@echo "... src/str.i"
	@echo "... src/str.s"
	@echo "... src/sys.o"
	@echo "... src/sys.i"
	@echo "... src/sys.s"
	@echo "... src/umse.o"
	@echo "... src/umse.i"
	@echo "... src/umse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

